---
include:
  - board: aum_left
    shield: lpm_view
    snippet: studio-rpc-usb-uart
  - board: aum_right
    shield: lpm_view
  - board: corne-v4_left
    snippet: studio-rpc-usb-uart
  - board: corne-v4_right
