---
include:
  - board: nice_nano_v2
    shield: aum_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: aum_left nice_view_adapter nice_view
  - board: corne-v4_left
    snippet: studio-rpc-usb-uart
  - board: corne-v4_right

